## application parameters
application_parameters:
  image_size: 224
  plot_reconstruction: False


## input modalities/transformations
input_parameters:
  input_modalities: ['rgb', 'noise']
  augmentation_list: ["flip", "zoom", "rotate"]
  bsif_computation: False

## model parameters
model_parameters:
  number_of_epochs: 50
  learning_rate: 0.0001
  batch_size: 10
  partial_layer: "intermediate_layer" # name of the partial layer to get activations. To perform the prediction with the entire model, set it to ""